[package]
name = "bff"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace        = true
axum                         = { workspace = true }
base64.workspace             = true
oidc                         = { path = "../oidc" }
redis                        = { workspace = true, features = ["tokio-comp", "connection-manager"] } 
reqwest                      = { workspace = true, features = ["stream"] } 
ring                         = { workspace = true }
serde.workspace              = true
serde_json.workspace         = true
subtle                       = { workspace = true } 
thiserror.workspace          = true
time.workspace               = true
tokio.workspace              = true
tracing.workspace            = true
tracing-subscriber.workspace = true   
